version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
